name: Build Workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      # Install dependencies and build frontend
      - name: Install and build frontend dependencies
        working-directory: ./client
        run: |
          echo "Installing frontend dependencies..."
          npm ci
          echo "Building frontend..."
          npm run build
