name: Main Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Set up
  setup:
    runs-on: ubuntu-latest

    steps:
      # Check out code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

  #lint:
  #needs: setup
  #uses: ./.github/workflows/lint.yml

  build:
    needs: setup
    uses: ./.github/workflows/build.yml

  #test:
  #needs: setup
  #uses: ./.github/workflows/test.yml

  #deploy:
  #needs: setup
  #uses: ./.github/workflows/deploy.yml
