name: Main Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  #lint:
  #uses: ./.github/workflows/lint.yml

  #test:
  #needs: setup
  #uses: ./.github/workflows/test.yml

  build:
    #needs: test
    uses: ./.github/workflows/build.yml

  #deploy:
  #needs: setup
  #uses: ./.github/workflows/deploy.yml
